### ISSUE TITLE
Does not work with Laravel 5.2

### ISSUE THREAD

**Issue by tylermarien** [wildbit/laravel-postmark-provider#4]
Currently does not work with Laravel 5.2. In Laravel 5.2 they removed the pretend mail configuration option. They also removed the setLogger method on the Mailer class.

**Comment by atheken** [comment]
@tylermarien Thanks for the head's up. We'll get this updated.

**Comment by tylermarien** [comment]
Fantastic. :+1:

**Comment by dmlogic** [comment]
+1 on this. I'll need to sort out something myself this week unless someone from Wildbit is already on it?

I'm thinking either bypass Laravel Mail and use the full PHP package, or extend Laravel's [`MailServiceProvider`](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Mail/MailServiceProvider.php) to return a different [`TransportManager`](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Mail/TransportManager.php) that supports Wildbit's [PostMark transport](https://github.com/wildbit/swiftmailer-postmark/blob/master/src/Postmark/Transport.php) via a "postmark" config value. That way we can still use the `MAIL_DRIVER` env variable and switch between "log" and "postmark" when testing

**Comment by atheken** [comment]
OK, I have added a new branch called `laravel-5.2-support` -- if @dmlogic and @tylermarien can set your provider versions to `dev-laravel-5.2-support` in your composer.json files and update to make sure this works for you, I'll release as v2.1 after I get confirmation.

Still, something is not right with this setup. I need to take some time to look at Laravel and see why those two features were removed, and how they should be supported. I think the Postmark driver should register with the default `MailServiceProvider`, rather than having our own subclass of it, but I need to investigate. Any tips you have on this would be greatly appreciated.

**Comment by dmlogic** [comment]
> I think the Postmark driver should register with the default MailServiceProvider

the supported drivers are hard-coded into the [`TransportManager`](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Mail/TransportManager.php), so you'd need to submit a PR and lobby Taylor to merge it. I'm sure there'd be plenty of support for that.

Explanations on the changes in 5.2 are [here](https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0)

**Comment by tylermarien** [comment]
It is working for me now. Thanks.

I agree that it would be nice to be able to register the driver with Laravel. Then you would be able to switch to the log driver on your dev environment (which seems to be the preferred method in 5.2, rather than using pretend).

**Comment by atheken** [comment]
@dmlogic On further research, it would appear that it is possible to extend the default `TransportManager` with a custom creation closure for Postmark by calling [`extend()`](https://github.com/laravel/framework/blob/7f62d81acb2001faafb21a32544464ebfc92476c/src/Illuminate/Support/Manager.php#L111) at the appropriate time.

That closure would be very similar to [this function](https://github.com/wildbit/laravel-postmark-provider/blob/master/src/Postmark/Adapters/LaravelMailProvider.php#L62).

In reality, this appears to completely bypass the need for this package, if this turns out to be true, we'll deprecate this package and provide Laravel integration instructions in the our SwiftMailer lib.

**Comment by dmlogic** [comment]
That looks like a great option - well found. I think "at the appropriate time" is going to be the tricky bit. I don't know the innards of Laravel well enough to know if the TransportManager can be accessed without introducing an alternative service provider.

For my project this week I'm going to roll with the standalone PHP package. Turns out I'll have thousands of notifications to send at once so I want to use batching (which makes it not appropriate to switch drivers anyway).

Thanks for your time so far and I'll check back in if you figure something out.

**Comment by pierrepavlov** [comment]
Just a bump here. Is it still the preferred way to use the `dev-laravel-5.2-support` version?

**Comment by atheken** [comment]
@pierrepavlov That branch was merged into `master`, so you should be able to use the latest from there.  

Also, have a look at this PR for Laravel, it looks like it was accepted and merged into 5.2, so if your Laravel instance is up to day, that approach is better: https://github.com/laravel/framework/pull/12509

**Comment by trevorgehman** [comment]
@atheken I would love to get some instructions on the recommended way to use Postmark with Laravel. Running into some trouble trying it myself...

**Comment by atheken** [comment]
@trevorgehman I think the latest versions of Laravel basically allow you to bypass this package and use our swift-mailer package instead. I will try to put together some instructions next week.

**Comment by trevorgehman** [comment]
@atheken If you could piece together some instructions that would be very helpful. Thanks!

**Comment by smayzes** [comment]
+1

**Comment by tnorthcutt** [comment]
@atheken Any plans to put together documentation for using Postmark + Laravel 5.2?

**Comment by tylerodonnell** [comment]
Hey Guys. I ran into this problem today. I wrote a little gist that should help you get started using
Postmarks swift-mailer package inside Laravel.

https://gist.github.com/TylerODonnell/e91f7d58293ba037c22d933f8652d022

**Comment by atheken** [comment]
Hey @TylerODonnell and @tnorthcutt, our current recommendation is to just use the SMTP provider that is available with Laravel out of the box. Since all of the Laravel email boils down to a simple message structure, there's really not a lot of benefit to using this driver instead. Here's an example config for SMTP using Laravel:

https://gist.github.com/atheken/fa58ec859667f391408f235174c14a90

Remember, you'll need to enable SMTP for each Postmark Server in order for mail to send properly.

Also, if you need deeper Postmark integration in your project, you should be able to use our full-featured Postmark-PHP library: https://github.com/wildbit/postmark-php
